apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      name: collector-pod
      labels:
        app: collector
    spec:
      containers:
      - name: collector-container
        image: anaslaaroussi/tweetoscope:tweet-collector-4.0
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      name: generator-pod
      labels:
        app: generator
    spec:
      containers:
      - name: generator-container
        image: anaslaaroussi/tweetoscope:tweet-generator-4.0
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: estimator-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: estimator
  template:
    metadata:
      name: estimator-pod
      labels:
        app: estimator
    spec:
      containers:
      - name: estimator-container
        image: anaslaaroussi/tweetoscope:tweet-estimator-4.0
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      name: predictor-pod
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor-container
        image: anaslaaroussi/tweetoscope:tweet-predictor-4.0
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learner
  template:
    metadata:
      name: learner-pod
      labels:
        app: learner
    spec:
      containers:
      - name: learner-container
        image: anaslaaroussi/tweetoscope:tweet-learner-4.0
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      name: monitor-pod
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor-container
        image: anaslaaroussi/tweetoscope:tweet-monitor-4.0
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      name: dashboard-pod
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard-container
        image: anaslaaroussi/tweetoscope:tweet-dashboard-4.0
        imagePullPolicy: IfNotPresent
